permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: 
cdn_url: 
lsi: false
safe: true
timezone: Asia/Beijing
auto: false 

paginate: 8
paginate_path: "page:num"

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

JB :
  IMAGE_PATH : http://coolshell.info/images

# presonal config
domain: http://coolshell.info
title: Lippi-浮生志
description: Draw my life with code
author: Scott.W
email: lockon547@gmail.com
github: lockon57

config:
  js_dir:
  img_dir:
  css_dir:

theme: jekyll-theme-minimal